# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180518_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isSold',
        ),
        migrations.AlterField(
            model_name='sales',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='myapp.Product'),
        ),
    ]
