# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180520_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSold',
            field=models.BooleanField(default=True),
        ),
    ]
